// src/app/components/navigation-buttons/navigation-buttons.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faChevronLeft,
  faChevronRight,
} from '@fortawesome/free-solid-svg-icons';
import {
  handleNextLevelGlobal,
  handlePreviousLevelGlobal,
} from '../../utils/handle-next-level';
import { NavigationService } from '../../services/navigation.service';

@Component({
  selector: 'app-navigation-buttons',
  standalone: true,
  imports: [CommonModule, FontAwesomeModule],
  templateUrl: './navigation-buttons.component.html',
  styleUrls: ['./navigation-buttons.component.scss'],
})
export class NavigationButtonsComponent {
  @Input() showOnlyPrevious: boolean = false;
  @Input() showOnlyNext: boolean = false;
  @Input() customNextLabel: string = 'Continuar';
  @Input() customPreviousLabel: string = 'Voltar';

  faChevronLeft = faChevronLeft;
  faChevronRight = faChevronRight;

  constructor(private navigationService: NavigationService) {}

  handleNextLevel(): void {
    handleNextLevelGlobal(this.navigationService);
  }
  handlePreviousLevel(): void {
    handlePreviousLevelGlobal(this.navigationService);
  }

  canGoNext(): boolean {
    // Permite avançar se não estiver no último nível
    const steps = this.navigationService.getSteps();
    return this.navigationService.getCurrentLevel() < steps.length - 1;
  }

  canGoPrevious(): boolean {
    // Permite voltar se não estiver no primeiro nível
    return this.navigationService.getCurrentLevel() > 0;
  }
}

<nav
  aria-label="Navegação de etapas"
  class="flex justify-center items-center p-5"
>
  <div class="flex gap-6 bg-transparent rounded-xl">
    <button
      *ngIf="!showOnlyNext"
      type="button"
      class="cursor-pointer flex items-center gap-2 px-4 py-2 rounded-lg text-green-600 font-semibold hover:bg-gray-100 bg-gray-50/90 border border-gray-200"
      (click)="handlePreviousLevel()"
      [disabled]="!canGoPrevious()"
    >
      <fa-icon [icon]="faChevronLeft" class="text-green-600 text-lg"></fa-icon>
      <span>{{ customPreviousLabel || "Voltar" }}</span>
    </button>
    <button
      *ngIf="!showOnlyPrevious"
      type="button"
      class="cursor-pointer flex items-center gap-2 px-4 py-2 rounded-lg text-white bg-green-600 hover:bg-green-700 border border-green-600"
      (click)="handleNextLevel()"
      [disabled]="!canGoNext()"
    >
      <span>{{ customNextLabel || "Continuar" }}</span>
      <fa-icon [icon]="faChevronRight" class="text-white text-lg"></fa-icon>
    </button>
  </div>
</nav>

// src/components/NavigationButtons.tsx
"use client";

import { FaChevronLeft, FaChevronRight } from "react-icons/fa";
import { useLevelContext } from "@/providers/LevelProvider";
import { scrollToTop } from "@/lib/scrollToTop";
import { useEffect, useState } from "react";

interface NavigationButtonsProps {
 className?: string;
 showOnlyNext?: boolean;
 showOnlyPrevious?: boolean;
 customNextLabel?: string;
 customPreviousLabel?: string;
}

export const NavigationButtons = ({
 className = "",
 showOnlyNext = false,
 showOnlyPrevious = false,
 customNextLabel = "Continuar",
 customPreviousLabel = "Voltar",
}: NavigationButtonsProps) => {
 const { nextLevel, previousLevel, canGoNext, canGoPrevious } =
  useLevelContext();
 const [isClient, setIsClient] = useState(false);

 useEffect(() => {
  setIsClient(true);
 }, []);

 if (!isClient) return null;

 return (
  <nav
   aria-label="Navegação de etapas"
   className={`flex justify-center items-center p-[20px] ${className}`}
  >
   <div className="flex gap-6 bg-transparent rounded-xl">
    {!showOnlyNext && (
     <button
      type="button"
      className="cursor-pointer flex items-center gap-2 px-4 py-2 rounded-lg text-green-600 font-semibold hover:bg-gray-100 bg-gray-50/90 border border-gray-200"
      onClick={() => {
       previousLevel();
       scrollToTop();
      }}
      disabled={!canGoPrevious()}
     >
      <FaChevronLeft />
      <span>{customPreviousLabel}</span>
     </button>
    )}
    {!showOnlyPrevious && (
     <button
      type="button"
      className="cursor-pointer flex items-center gap-2 px-4 py-2 rounded-lg text-white bg-green-600 hover:bg-green-700 border border-green-600"
      onClick={() => {
       nextLevel();
       scrollToTop();
      }}
      disabled={!canGoNext()}
     >
      <span>{customNextLabel}</span>
      <FaChevronRight />
     </button>
    )}
   </div>
  </nav>
 );
};
