// src/components/VehicleInfo.tsx
import React from "react";
import { FaInfoCircle } from "react-icons/fa";

interface VehicleInfoProps {
 selectedVehicle: "motorcycle" | "car" | null;
}

export const VehicleInfo: React.FC<VehicleInfoProps> = ({
 selectedVehicle,
}) => {
 if (!selectedVehicle) return null;
 return (
  <div className="bg-green-50 p-4 rounded-lg border border-green-200 mb-8 flex items-start">
   <FaInfoCircle className="text-green-600 mt-1 mr-3 flex-shrink-0" />
   <div>
    <p className="text-green-800 font-medium">
     Veículo selecionado:{" "}
     <span className="font-bold">
      {selectedVehicle === "motorcycle" ? "Moto" : "Carro"}
     </span>
    </p>
    <p className="text-green-600 text-sm mt-1">
     Veja abaixo as regras específicas para seu veículo
    </p>
   </div>
  </div>
 );
};

export default VehicleInfo;

// src/app/components/vehicle-info/vehicle-info.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import {
  faInfoCircle,
  faMotorcycle,
  faCar,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-vehicle-info',
  templateUrl: './vehicle-info.component.html',
  styleUrls: ['./vehicle-info.component.scss'],
})
export class VehicleInfoComponent {
  @Input() selectedVehicle: 'motorcycle' | 'car' | null = null;
  @Input() showSelector: boolean = false;
  @Output() vehicleSelected = new EventEmitter<'motorcycle' | 'car'>();

  // Font Awesome icons
  faInfoCircle = faInfoCircle;
  faMotorcycle = faMotorcycle;
  faCar = faCar;

  selectVehicle(vehicle: 'motorcycle' | 'car'): void {
    this.vehicleSelected.emit(vehicle);
  }
}

<div
  class="bg-green-50 p-4 rounded-lg border border-green-200 mb-4 flex items-start"
>
  <div class="text-green-600 mt-1 mr-3 flex-shrink-0">i</div>
  <div>
    <p class="text-green-800 font-medium">
      Veículo selecionado:
      <span class="font-bold">{{
        selectedVehicle === "motorcycle" ? "Moto" : "Carro"
      }}</span>
    </p>
    <p class="text-green-600 text-sm mt-1">
      {{
        selectedVehicle === "motorcycle"
          ? "Moto: meta diária de 5 pontos. Cada ponto extra soma R$ 15."
          : "Carro: meta diária de 6 pontos. Cada ponto extra soma R$ 15."
      }}
    </p>
  </div>
</div>
